<?php

require_once 'D:/BobydoInc/Website/websiteShareposts/shareposts/app/services/Factory.php';
require_once 'D:/BobydoInc/Website/websiteShareposts/shareposts/app/DAL/UserDAL.php';
require_once 'D:/BobydoInc/Website/websiteShareposts/shareposts/app/DAL/PostDAL.php';
require_once 'D:/BobydoInc/Website/websiteShareposts/shareposts/app/DAL/IUserDAL.php';
require_once 'D:/BobydoInc/Website/websiteShareposts/shareposts/app/DAL/IPostDAL.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-09 at 00:28:27.
 */
class FactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Factory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Factory::AddUser
     * @todo   Implement testAddUser().
     */
    public function testAddUser() {
        // Remove the following lines when you implement this test.
        $test_data=[
                    'name' => 'cathy_test',
                    'email' => 'cathy_test@gmail.com',
                    'password' => 'test',
                    'confirm_password' => 'test',
                    ];
        $this->object->AddUser($test_data);
        $this->assertTrue($this->object->AddUser());
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
    }

    /**
     * @covers Factory::Login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::FindUserByEmail
     * @todo   Implement testFindUserByEmail().
     */
    public function testFindUserByEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::GetUserById
     * @todo   Implement testGetUserById().
     */
    public function testGetUserById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::GetPosts
     * @todo   Implement testGetPosts().
     */
    public function testGetPosts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::AddPost
     * @todo   Implement testAddPost().
     */
    public function testAddPost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::UpdatePost
     * @todo   Implement testUpdatePost().
     */
    public function testUpdatePost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::GetPostById
     * @todo   Implement testGetPostById().
     */
    public function testGetPostById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::DeletePost
     * @todo   Implement testDeletePost().
     */
    public function testDeletePost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
