<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-11 at 01:24:25.
 */
require_once APPROOT . '/controllers/Users.php';
require_once APPROOT . '/services/IUserService.php';
use PHPUnit\Framework\TestCase;

class UsersTest extends TestCase {

    /**
     * @var Users
     */
    protected $object;
    protected $expect;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Users;
        $this->expect =array (
                        'email' => 'cathy@gamil.com',
                        'password' => '111111',
                        'email_err' => '',
                        'password_err' => '',      
                        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

//    /**
//     * @covers Users::register
//     * @todo   Implement testRegister().
//     */
//    public function testRegister() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Users::login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.

        //Arrange
        
        $observer = $this->createMock(IUserService::class);

        $observer->expects($this->once())
                 ->method('Login')
                 ->willreturn($this->expect);
//        $this->object->Login($_POST['email'], $_POST['password']);
        $this->object->Login();
//        print_r($observer);
        $this->assertEquals($this->expect, $observer->Login('cathy@gmail.com', '111111'));
    }

//    /**
//     * @covers Users::createUserSession
//     * @todo   Implement testCreateUserSession().
//     */
//    public function testCreateUserSession() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers Users::logout
//     * @todo   Implement testLogout().
//     */
//    public function testLogout() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

}
